# Dockerfile-stripe

# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project
COPY . .

# Run Gunicorn with the Stripe webhook app
CMD ["gunicorn", "-c", "config/gunicorn/gunicorn_stripe_config.py", "src.wsgi_stripe:app"]
