# Dockerfile-bot

# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

COPY config/other_configs/requirements.txt requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project
COPY src/ src/

# Run bot.py when the container launches
CMD ["python", "src/bot.py"]



# docker build -t discord-age-verification-service -f Dockerfile-bot .
# docker run -d -p 5000:5000 --name discord-age-verification-service discord-age-verification-service