# Dockerfile-stripe-webhook

# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY config/other_configs/requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code and Gunicorn configuration file
COPY src/ /app/src/
COPY config/gunicorn/gunicorn_stripe_config.py /app/config/gunicorn_stripe_config.py

# Expose the port
EXPOSE 5431

# Run gunicorn server
CMD ["gunicorn", "-c", "/app/config/gunicorn_stripe_config.py", "src.wsgi_stripe:app"]
