services:
  discord-bot:
    build:
      context: ../../
      dockerfile: docker/Dockerfile-bot
    ports:
      - "5000:5000"
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      # - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_VERIFICATION=${DATABASE_URL_VERIFICATION}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
      - DOB_KEY=${DOB_KEY}

  stripe-webhook:
    build:
      context: ../../
      dockerfile: docker/Dockerfile-stripe-webhook
    ports:
      - "5431:5431"
    environment:
      - DATABASE_URL_DJ=${DATABASE_URL_DJ}
      - DATABASE_URL_VERIFICATION=${DATABASE_URL_VERIFICATION}
      - STRIPE_RESTRICTED_SECRET_KEY=${STRIPE_RESTRICTED_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
      - DOB_KEY=${DOB_KEY}

  subscription-manager:
    build:
      context: ../../
      dockerfile: docker/Dockerfile-subscription-manager
    ports:
      - "5433:5433"
    environment:
      - DATABASE_URL_DJ=${DATABASE_URL_DJ}
      - DATABASE_URL_VERIFICATION=${DATABASE_URL_VERIFICATION}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PAYMENT_WEBHOOK_SECRET=${STRIPE_PAYMENT_WEBHOOK_SECRET}

  subscription-checker:
    build:
      context: ../../
      dockerfile: docker/Dockerfile-subscription-checker